apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    {{- include "pedido-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  db_user: {{ .Values.db.auth.username | quote }}
  db_password: {{ .Values.db.auth.password | quote }}