apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pedidoapi
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/cordovalen/PedidoApi
    targetRevision: HEAD
    path: helm/pedidoapi
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
