{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pedidoapi.fullname" . }}
  labels:
    {{- include "pedidoapi.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: api/$2
spec:
  ingressClassName: {{ .Values.ingress.className}}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "pedidoapi.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
{{- end }}
