apiVersion: v1
kind: Service
metadata:
  name: {{ include "pedidoapi.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:  
  {{- include "pedidoapi.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
