apiVersion: v1
kind: Service
metadata:
  name: {{ include "pedidoapi.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:  
    app: pedidoapi
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
