name: CI/CD Pipeline for PedidoApi

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
    
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build with .NET
        run: dotnet build PedidoApi.sln --no-restore  
  
  docker_build_and_push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pedidosapp:${{ env.IMAGE_TAG }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/pedidosapp:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/pedidosapp:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pedidosapp:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/pedidosapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    steps:
      - name: Clone deployment repository
        env:
          EXTERNAL_REPO: 'https://github.com/cordovalen/PedidoApi'
          BRANCH: 'master'
        run: |
          git clone --single-branch --branch ${{ env.BRANCH }} ${{ env.EXTERNAL_REPO }} PedidoApi
          cd PedidoApi
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.44.3
      - name: Set new image tag
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/pedidosapp
          NEW_TAG: ${{ github.run_number }}" >> $GITHUB_ENV
        run: |
          cd PedidoApi
          yq eval ".image.tag = \"${{ env.NEW_TAG }}\"" -i helm/pedidoapi/values.yaml
      - name: Commit changes in external repo
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          cd PedidoApi
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Actualiza imagen a ${{ env.IMAGE_NAME }}:${{ env.NEW_TAG }}"
          git remote set-url origin https://cordovalen:${{ env.GITHUB_TOKEN }}@github.com/cordovalen/PedidoApi.git
          git push origin master
    

